# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190704_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='963217296@qq.com', max_length=50, verbose_name='邮箱'),
        ),
    ]
