# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户名'),
        ),
    ]
